package com.massadas.godot_eskills;

import static android.app.Activity.RESULT_OK;

import android.app.Activity;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.content.pm.ResolveInfo;
import android.net.Uri;
import android.util.Log;

import org.godotengine.godot.Godot;
import org.godotengine.godot.plugin.UsedByGodot;

import java.util.List;

public class Eskills extends Godot.SingletonBase {
    private static final int REQUEST_CODE = 123;
    private static final String SESSION = "SESSION";
    private static final String TAG = "godot";

    protected Activity activity = null;
    private String sessionToken;

    @Override
    protected void onMainActivityResult(int requestCode, int resultCode, Intent data) {
        Log.d(TAG, "onActivityResult called");
        if (requestCode == REQUEST_CODE && resultCode == RESULT_OK) {
            sessionToken = data.getStringExtra(SESSION);
            Log.d(TAG, "sessionToken: " + sessionToken);
        }
    }

    @UsedByGodot
    public String getSessionToken() {
        return sessionToken;
    }

    @UsedByGodot
    public void startMatch(String url) {
        Log.d(TAG, "url: " + url);
        Intent intent = buildTargetIntent(url);
        try {
            activity.startActivityForResult(intent, REQUEST_CODE);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method generates the intent with the provided One Step URL to target
     * the
     * AppCoins Wallet.
     *
     * @param url The url that generated by following the One Step payment rules
     * @return The intent used to call the wallet
     */
    private Intent buildTargetIntent(String url) {
        Intent intent = new Intent(Intent.ACTION_VIEW);
        intent.setData(Uri.parse(url));
        // Check if there is an application that can process the AppCoins Billing
        // flow
        PackageManager packageManager =
                activity.getApplicationContext().getPackageManager();
        List<ResolveInfo> appsList = packageManager
                .queryIntentActivities(intent,
                        PackageManager.MATCH_DEFAULT_ONLY);
        for (ResolveInfo app : appsList) {
            if (app.activityInfo.packageName.equals("cm.aptoide.pt")) {
                // If there's aptoide installed always choose Aptoide as default to open
                // url
                intent.setPackage(app.activityInfo.packageName);
                break;
            } else if (app.activityInfo.packageName.equals("com.appcoins.wallet")) {
                // If Aptoide is not installed and wallet is installed then choose Wallet
                // as default to open url
                intent.setPackage(app.activityInfo.packageName);
            }
        }
        return intent;
    }

    /**
     * Initilization of the Singleton
     */
    static public Godot.SingletonBase initialize(Activity p_activity) {
        return new Eskills(p_activity);
    }

    public Eskills(Activity activity) {
        this.activity = activity;
    }
}